language: python
python:
  - 3.7.4

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: __token__
  on:
    tags: true
  password:
    secure: jugT515+srBgopSKFKGZtGf+w3SbykBnV1itodF/gRZiPWJ/S7G0Zr8sIKjjl3FpTbv0isJEZR7k65A5dY83uy+6hD8+t7Hi7KBzs3FT84k4EJfvgMcXB3FdDHGyvMfxQJyXvwixxJvqxtk9KjiQ3KHz5dE8C5EFqAh6WPhUyE2Rnm//9rI7bq5B2zrQJ31B5qwDmNKNEwE2furGIMBe4N9zZaKFG0xLXpS9yh8dQhyUSN4ZpahVs5S0PHXFpiyfYwbznulix5Ztr6e8n9eUQlc/Rh708sztEEaVGClmmdFfZfqOo9+skdUd677FdeZ2NA3HRFq5Tx+Z2NotKdRLezpnKH6A5Tr+eB0YaEFe2/L3a4o1Xo/KJPNCzcX2Am4F0EBHClVF11xkeS1OiZ8l7F3LYq5CW9A7JQQ2AZ3HPuo7IXVK5naCt9LjRoeKEI51srCU5A/vbP/97bq1zQ9CdVtJOnj84uM4lKCn1vtWeIp92/7DbFiPapREmzUKcnQHcBYAgXpiE6Ttp0xQR4M9kMQyQfghQI6c9CHrgksyfghLrIubzAksD6z7mDIaz8/ZR+mkk/XNpM6nD0FGvXydtWmtPNUFVcNKP6WGOGJxnnUtmWfyrEtC4oMH9Nf09milkHcjYvNhlX/qfnPPpHpC9Xsi8abvsFQX6OlnQRncwJA=

script:
  - flake8 pyjuicenet
